const intialGameState = {
  yourId: "",
  yourColor: "",
  currentTurn: "",
  diceResults: ["?", "?"],
  board: {
    whiteOut: [],
    blackOut: [],
    0: [],
    1: [
      { id: 1, color: "black" },
      { id: 2, color: "black" },
    ],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [
      { id: 26, color: "white" },
      { id: 27, color: "white" },
      { id: 28, color: "white" },
      { id: 29, color: "white" },
      { id: 30, color: "white" },
    ],
    7: [],
    8: [
      { id: 23, color: "white" },
      { id: 24, color: "white" },
      { id: 25, color: "white" },
    ],
    9: [],
    10: [],
    11: [],
    12: [
      { id: 18, color: "black" },
      { id: 19, color: "black" },
      { id: 20, color: "black" },
      { id: 21, color: "black" },
      { id: 22, color: "black" },
    ],
    13: [
      { id: 3, color: "white" },
      { id: 4, color: "white" },
      { id: 5, color: "white" },
      { id: 6, color: "white" },
      { id: 7, color: "white" },
    ],
    14: [],
    15: [],
    16: [],
    17: [
      { id: 8, color: "black" },
      { id: 9, color: "black" },
      { id: 10, color: "black" },
    ],
    18: [],
    19: [
      { id: 11, color: "black" },
      { id: 12, color: "black" },
      { id: 13, color: "black" },
      { id: 14, color: "black" },
      { id: 15, color: "black" },
    ],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [
      { id: 16, color: "white" },
      { id: 17, color: "white" },
    ],
    25: [],
  },
};

export { intialGameState };

const testBoard = {
  board: {
    whiteOut: [],
    blackOut: [],
    0: [{ id: 21, color: "black" }],
    1: [{ id: 18, color: "white" }, { id: 19, color: "white" }, ,],
    2: [
      { id: 21, color: "white" },
      { id: 22, color: "white" },
    ],
    3: [
      { id: 21, color: "white" },
      { id: 22, color: "white" },
    ],
    4: [
      { id: 21, color: "white" },
      { id: 22, color: "white" },
    ],
    5: [
      { id: 21, color: "white" },
      { id: 22, color: "white" },
    ],
    6: [
      { id: 21, color: "white" },
      { id: 22, color: "white" },
    ],
    7: [],
    8: [],
    9: [],
    10: [],
    11: [],
    12: [],
    13: [],
    14: [],
    15: [],
    16: [],
    17: [],
    18: [],
    19: [],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [],
    25: [],
  },
};

const normalBoard = {
  board: {
    whiteOut: [],
    blackOut: [],
    0: [],
    1: [
      { id: 1, color: "black" },
      { id: 2, color: "black" },
    ],
    2: [],
    3: [],
    4: [],
    5: [],
    6: [
      { id: 26, color: "white" },
      { id: 27, color: "white" },
      { id: 28, color: "white" },
      { id: 29, color: "white" },
      { id: 30, color: "white" },
    ],
    7: [],
    8: [
      { id: 23, color: "white" },
      { id: 24, color: "white" },
      { id: 25, color: "white" },
    ],
    9: [],
    10: [],
    11: [],
    12: [
      { id: 18, color: "black" },
      { id: 19, color: "black" },
      { id: 20, color: "black" },
      { id: 21, color: "black" },
      { id: 22, color: "black" },
    ],
    13: [
      { id: 3, color: "white" },
      { id: 4, color: "white" },
      { id: 5, color: "white" },
      { id: 6, color: "white" },
      { id: 7, color: "white" },
    ],
    14: [],
    15: [],
    16: [],
    17: [
      { id: 8, color: "black" },
      { id: 9, color: "black" },
      { id: 10, color: "black" },
    ],
    18: [],
    19: [
      { id: 11, color: "black" },
      { id: 12, color: "black" },
      { id: 13, color: "black" },
      { id: 14, color: "black" },
      { id: 15, color: "black" },
    ],
    20: [],
    21: [],
    22: [],
    23: [],
    24: [
      { id: 16, color: "white" },
      { id: 17, color: "white" },
    ],
    25: [],
  },
};
